<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0;net472</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Rtp\Data\img_jpg_0.jpg" />
	  <None Remove="Rtp\Data\jpeg_0.rtp" />
	  <None Remove="Rtp\Data\jpeg_1.rtp" />
	  <None Remove="Rtp\Data\jpeg_2.rtp" />
	  <None Remove="Sdp\Data\test4.sdp" />
	  <None Remove="Sdp\Data\test5.sdp" />
	</ItemGroup>

	<ItemGroup>
		<CodeAnalysisDependentAssemblyPaths Condition=" '$(VS100COMNTOOLS)' != '' " Include="$(VS100COMNTOOLS)..\IDE\PrivateAssemblies">
			<Visible>False</Visible>
		</CodeAnalysisDependentAssemblyPaths>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Rtp\Data\img_jpg_0.jpg" />
		<EmbeddedResource Include="Rtp\Data\jpeg_0.rtp" />
		<EmbeddedResource Include="Rtp\Data\jpeg_1.rtp" />
		<EmbeddedResource Include="Rtp\Data\jpeg_2.rtp" />
		<EmbeddedResource Include="Sdp\Data\test1.sdp" />
		<EmbeddedResource Include="Sdp\Data\test2.sdp" />
		<EmbeddedResource Include="Sdp\Data\test3.sdp" />
		<EmbeddedResource Include="Sdp\Data\test4.sdp" />
		<EmbeddedResource Include="Sdp\Data\test5.sdp" />
		<EmbeddedResource Include="Sdp\Data\test6.sdp" />
		<EmbeddedResource Include="Sdp\Data\test7.sdp" />
		<None Remove="Sdp\Data\test8.sdp" />
		<EmbeddedResource Include="Sdp\Data\test8.sdp" />
		<None Remove="Sdp\Data\test9.sdp" />
		<EmbeddedResource Include="Sdp\Data\test9.sdp" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\RTSP\RTSP.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NSubstitute" Version="5.3.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit.Analyzers" Version="4.6.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
	</ItemGroup>
</Project>